name: lens-conversion
channels:
  - conda-forge
dependencies:
  - python=3.8
  - jupyterlab
  - bokeh==1.4.0
  - watermark
  - xarray
  - netcdf4
  - intake
  - zarr
  - s3fs
  - awscli
  - dask=2.14.0
  - distributed=2.14.0
  - numpy
  - ipywidgets
  - pip
  #- intake-esm>2020.3.16.2
  - dask-jobqueue
  - tqdm
  - matplotlib
  - pip:
       - ncar-jobqueue
       - git+https://github.com/NCAR/intake-esm.git@master
